# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jduarte/Documents/GitHub/CR/Repository/Generic_counter/Generic_counter.cache/wt [current_project]
set_property parent.project_path C:/Users/jduarte/Documents/GitHub/CR/Repository/Generic_counter/Generic_counter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/jduarte/Documents/GitHub/CR/Repository/Generic_counter/Generic_counter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library work {
  C:/Users/jduarte/Documents/GitHub/CR/Repository/Generic_counter/Generic_counter.srcs/sources_1/imports/new/ex6.vhd
  C:/Users/jduarte/Documents/GitHub/CR/Repository/Generic_counter/Generic_counter.srcs/sources_1/imports/new/clock_divider.vhd
  C:/Users/jduarte/Documents/GitHub/CR/Repository/Generic_counter/Generic_counter.srcs/sources_1/imports/new/ex6_mapping.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jduarte/Documents/GitHub/CR/Repository/Generic_counter/Generic_counter.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/jduarte/Documents/GitHub/CR/Repository/Generic_counter/Generic_counter.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc]


synth_design -top ex6_mapping -part xc7a100tcsg324-3


write_checkpoint -force -noxdef ex6_mapping.dcp

catch { report_utilization -file ex6_mapping_utilization_synth.rpt -pb ex6_mapping_utilization_synth.pb }
