# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir K:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.cache/wt [current_project]
set_property parent.project_path K:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths k:/CRExamples2017/AT8/ZyBo2017 [current_project]
set_property ip_output_repo k:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib K:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.srcs/sources_1/bd/B/hdl/B_wrapper.vhd
add_files K:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.srcs/sources_1/bd/B/B.bd
set_property used_in_implementation false [get_files -all k:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.srcs/sources_1/bd/B/ip/B_InterfaceKeypad_0_0/constrs_1/imports/ZyBo/ZYBO_Master.xdc]
set_property used_in_implementation false [get_files -all k:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.srcs/sources_1/bd/B/ip/B_ToDisp_0_0/constrs_1/imports/ZyBoDef2015/ZYBO_Master.xdc]
set_property used_in_implementation false [get_files -all K:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.srcs/sources_1/bd/B/B_ooc.xdc]
set_property is_locked true [get_files K:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.srcs/sources_1/bd/B/B.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc K:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.srcs/constrs_1/imports/ZyBo/ZYBO_Master.xdc
set_property used_in_implementation false [get_files K:/CRExamples2017/AT8/FromKeypadToDisplays/FromKeypadToDisplays.srcs/constrs_1/imports/ZyBo/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top B_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef B_wrapper.dcp

catch { report_utilization -file B_wrapper_utilization_synth.rpt -pb B_wrapper_utilization_synth.pb }
