# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ZyBo/ZYBO_Master.xdc

# Block Designs: bd/B/B.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B || ORIG_REF_NAME==B}]

# IP: bd/B/ip/B_InterfaceKeypad_0_0/B_InterfaceKeypad_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B_InterfaceKeypad_0_0 || ORIG_REF_NAME==B_InterfaceKeypad_0_0}]

# IP: bd/B/ip/B_ToDisp_0_0/B_ToDisp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B_ToDisp_0_0 || ORIG_REF_NAME==B_ToDisp_0_0}]

# IP: bd/B/ip/B_xlslice_0_0/B_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B_xlslice_0_0 || ORIG_REF_NAME==B_xlslice_0_0}]

# IP: bd/B/ip/B_xlslice_1_0/B_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B_xlslice_1_0 || ORIG_REF_NAME==B_xlslice_1_0}]

# XDC: bd/B/ip/B_InterfaceKeypad_0_0/constrs_1/imports/ZyBo/ZYBO_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==B_InterfaceKeypad_0_0 || ORIG_REF_NAME==B_InterfaceKeypad_0_0}] {/U0 }]/U0 ]]

# XDC: bd/B/ip/B_ToDisp_0_0/constrs_1/imports/ZyBoDef2015/ZYBO_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==B_ToDisp_0_0 || ORIG_REF_NAME==B_ToDisp_0_0}] {/U0 }]/U0 ]]

# XDC: bd/B/B_ooc.xdc
