set_property SRC_FILE_INFO {cfile:C:/Users/jduarte/Desktop/CR/Aula1/ex4/ex4.srcs/constrs_1/imports/new/SDR_const.xdc rfile:../../../ex4.srcs/constrs_1/imports/new/SDR_const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {led[3]}]
