# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/teste/teste.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==teste || ORIG_REF_NAME==teste}]

# IP: bd/teste/ip/teste_ClkDividerN_0_0_1/teste_ClkDividerN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==teste_ClkDividerN_0_0 || ORIG_REF_NAME==teste_ClkDividerN_0_0}]

# IP: bd/teste/ip/teste_xlconstant_0_0_1/teste_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==teste_xlconstant_0_0 || ORIG_REF_NAME==teste_xlconstant_0_0}]

# IP: bd/teste/ip/teste_xlslice_0_0_1/teste_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==teste_xlslice_0_0 || ORIG_REF_NAME==teste_xlslice_0_0}]

# IP: bd/teste/ip/teste_xlslice_1_0/teste_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==teste_xlslice_1_0 || ORIG_REF_NAME==teste_xlslice_1_0}]

# IP: bd/teste/ip/teste_counter_between_x_and_y_1_0/teste_counter_between_x_and_y_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==teste_counter_between_x_and_y_1_0 || ORIG_REF_NAME==teste_counter_between_x_and_y_1_0}]

# XDC: bd/teste/teste_ooc.xdc
