# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex2_top/ex2_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top || ORIG_REF_NAME==ex2_top}]

# IP: bd/ex2_top/ip/ex2_top_blk_mem_gen_0_0/ex2_top_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_blk_mem_gen_0_0 || ORIG_REF_NAME==ex2_top_blk_mem_gen_0_0}]

# IP: bd/ex2_top/ip/ex2_top_xlconstant_0_0/ex2_top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlconstant_0_0 || ORIG_REF_NAME==ex2_top_xlconstant_0_0}]

# IP: bd/ex2_top/ip/ex2_top_xlconstant_1_0/ex2_top_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlconstant_1_0 || ORIG_REF_NAME==ex2_top_xlconstant_1_0}]

# IP: bd/ex2_top/ip/ex2_top_concat_memory_0_0/ex2_top_concat_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_concat_memory_0_0 || ORIG_REF_NAME==ex2_top_concat_memory_0_0}]

# IP: bd/ex2_top/ip/ex2_top_BinToBCD16_0_0/ex2_top_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_BinToBCD16_0_0 || ORIG_REF_NAME==ex2_top_BinToBCD16_0_0}]

# IP: bd/ex2_top/ip/ex2_top_xlconstant_2_0/ex2_top_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlconstant_2_0 || ORIG_REF_NAME==ex2_top_xlconstant_2_0}]

# IP: bd/ex2_top/ip/ex2_top_EightDispControl_0_0/ex2_top_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_EightDispControl_0_0 || ORIG_REF_NAME==ex2_top_EightDispControl_0_0}]

# IP: bd/ex2_top/ip/ex2_top_xlconstant_0_1/ex2_top_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlconstant_0_1 || ORIG_REF_NAME==ex2_top_xlconstant_0_1}]

# IP: bd/ex2_top/ip/ex2_top_number_of_ones_0_1/ex2_top_number_of_ones_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_number_of_ones_0_1 || ORIG_REF_NAME==ex2_top_number_of_ones_0_1}]

# IP: bd/ex2_top/ip/ex2_top_IterativeSorterFSM_0_0/ex2_top_IterativeSorterFSM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_IterativeSorterFSM_0_0 || ORIG_REF_NAME==ex2_top_IterativeSorterFSM_0_0}]

# XDC: bd/ex2_top/ex2_top_ooc.xdc
