# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex2_top/ex2_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top || ORIG_REF_NAME==ex2_top}]

# IP: bd/ex2_top/ip/ex2_top_max_min_FSM_0_0/ex2_top_max_min_FSM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_max_min_FSM_0_0 || ORIG_REF_NAME==ex2_top_max_min_FSM_0_0}]

# IP: bd/ex2_top/ip/ex2_top_blk_mem_gen_0_0/ex2_top_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_blk_mem_gen_0_0 || ORIG_REF_NAME==ex2_top_blk_mem_gen_0_0}]

# IP: bd/ex2_top/ip/ex2_top_Mux2_1_0_0/ex2_top_Mux2_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_Mux2_1_0_0 || ORIG_REF_NAME==ex2_top_Mux2_1_0_0}]

# IP: bd/ex2_top/ip/ex2_top_EightDispControl_0_0/ex2_top_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_EightDispControl_0_0 || ORIG_REF_NAME==ex2_top_EightDispControl_0_0}]

# IP: bd/ex2_top/ip/ex2_top_xlslice_0_0/ex2_top_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlslice_0_0 || ORIG_REF_NAME==ex2_top_xlslice_0_0}]

# IP: bd/ex2_top/ip/ex2_top_xlslice_0_1/ex2_top_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlslice_0_1 || ORIG_REF_NAME==ex2_top_xlslice_0_1}]

# IP: bd/ex2_top/ip/ex2_top_xlslice_0_2/ex2_top_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlslice_0_2 || ORIG_REF_NAME==ex2_top_xlslice_0_2}]

# IP: bd/ex2_top/ip/ex2_top_xlslice_0_3/ex2_top_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlslice_0_3 || ORIG_REF_NAME==ex2_top_xlslice_0_3}]

# IP: bd/ex2_top/ip/ex2_top_xlslice_0_4/ex2_top_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlslice_0_4 || ORIG_REF_NAME==ex2_top_xlslice_0_4}]

# IP: bd/ex2_top/ip/ex2_top_xlslice_0_5/ex2_top_xlslice_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlslice_0_5 || ORIG_REF_NAME==ex2_top_xlslice_0_5}]

# IP: bd/ex2_top/ip/ex2_top_xlslice_0_6/ex2_top_xlslice_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlslice_0_6 || ORIG_REF_NAME==ex2_top_xlslice_0_6}]

# IP: bd/ex2_top/ip/ex2_top_xlslice_6_0/ex2_top_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_top_xlslice_6_0 || ORIG_REF_NAME==ex2_top_xlslice_6_0}]

# XDC: bd/ex2_top/ex2_top_ooc.xdc
