# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.cache/wt [current_project]
set_property parent.project_path C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2
  c:/Users/jduarte/Documents/GitHub/CR/Repository
} [current_project]
set_property ip_output_repo c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex1/vector512_random.coe
read_vhdl -library xil_defaultlib C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/hdl/ex2_top_wrapper.vhd
add_files C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/ex2_top.bd
set_property used_in_implementation false [get_files -all c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/ip/ex2_top_max_min_FSM_0_0/ex2.srcs/constrs_1/imports/CR/Nexys4_Master.xdc]
set_property used_in_implementation false [get_files -all c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/ip/ex2_top_blk_mem_gen_0_0/ex2_top_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/ex2_top_ooc.xdc]
set_property is_locked true [get_files C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/ex2_top.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/constrs_1/imports/CR/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/constrs_1/imports/CR/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ex2_top_wrapper -part xc7a100tcsg324-3


write_checkpoint -force -noxdef ex2_top_wrapper.dcp

catch { report_utilization -file ex2_top_wrapper_utilization_synth.rpt -pb ex2_top_wrapper_utilization_synth.pb }
