# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex1/ex1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1 || ORIG_REF_NAME==ex1}]

# IP: bd/ex1/ip/ex1_blk_mem_gen_0_0/ex1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_blk_mem_gen_0_0 || ORIG_REF_NAME==ex1_blk_mem_gen_0_0}]

# IP: bd/ex1/ip/ex1_dist_mem_gen_0_0/ex1_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_dist_mem_gen_0_0 || ORIG_REF_NAME==ex1_dist_mem_gen_0_0}]

# IP: bd/ex1/ip/ex1_dist_mem_gen_1_0/ex1_dist_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_dist_mem_gen_1_0 || ORIG_REF_NAME==ex1_dist_mem_gen_1_0}]

# IP: bd/ex1/ip/ex1_xlslice_0_0/ex1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_0_0 || ORIG_REF_NAME==ex1_xlslice_0_0}]

# IP: bd/ex1/ip/ex1_counter_generic_0_0/ex1_counter_generic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_counter_generic_0_0 || ORIG_REF_NAME==ex1_counter_generic_0_0}]

# IP: bd/ex1/ip/ex1_xlconstant_0_0/ex1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconstant_0_0 || ORIG_REF_NAME==ex1_xlconstant_0_0}]

# IP: bd/ex1/ip/ex1_xlconstant_1_0/ex1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconstant_1_0 || ORIG_REF_NAME==ex1_xlconstant_1_0}]

# IP: bd/ex1/ip/ex1_Mux4_1_0_0/ex1_Mux4_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_Mux4_1_0_0 || ORIG_REF_NAME==ex1_Mux4_1_0_0}]

# IP: bd/ex1/ip/ex1_xlconcat_0_0/ex1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconcat_0_0 || ORIG_REF_NAME==ex1_xlconcat_0_0}]

# IP: bd/ex1/ip/ex1_xlconcat_0_1/ex1_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconcat_0_1 || ORIG_REF_NAME==ex1_xlconcat_0_1}]

# IP: bd/ex1/ip/ex1_xlconcat_1_0/ex1_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconcat_1_0 || ORIG_REF_NAME==ex1_xlconcat_1_0}]

# IP: bd/ex1/ip/ex1_xlslice_1_0/ex1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_1_0 || ORIG_REF_NAME==ex1_xlslice_1_0}]

# IP: bd/ex1/ip/ex1_xlslice_2_0/ex1_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_2_0 || ORIG_REF_NAME==ex1_xlslice_2_0}]

# IP: bd/ex1/ip/ex1_xlconcat_3_1/ex1_xlconcat_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconcat_3_1 || ORIG_REF_NAME==ex1_xlconcat_3_1}]

# IP: bd/ex1/ip/ex1_xlconstant_2_0/ex1_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconstant_2_0 || ORIG_REF_NAME==ex1_xlconstant_2_0}]

# IP: bd/ex1/ip/ex1_BinToBCD16_0_1/ex1_BinToBCD16_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_BinToBCD16_0_1 || ORIG_REF_NAME==ex1_BinToBCD16_0_1}]

# IP: bd/ex1/ip/ex1_BinToBCD16_1_0/ex1_BinToBCD16_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_BinToBCD16_1_0 || ORIG_REF_NAME==ex1_BinToBCD16_1_0}]

# IP: bd/ex1/ip/ex1_xlconstant_3_0/ex1_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconstant_3_0 || ORIG_REF_NAME==ex1_xlconstant_3_0}]

# IP: bd/ex1/ip/ex1_EightDispControl_0_0/ex1_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_EightDispControl_0_0 || ORIG_REF_NAME==ex1_EightDispControl_0_0}]

# IP: bd/ex1/ip/ex1_util_vector_logic_0_0/ex1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_util_vector_logic_0_0 || ORIG_REF_NAME==ex1_util_vector_logic_0_0}]

# IP: bd/ex1/ip/ex1_xlconstant_5_0/ex1_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconstant_5_0 || ORIG_REF_NAME==ex1_xlconstant_5_0}]

# IP: bd/ex1/ip/ex1_counter_generic_1_0/ex1_counter_generic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_counter_generic_1_0 || ORIG_REF_NAME==ex1_counter_generic_1_0}]

# IP: bd/ex1/ip/ex1_counter_generic_1_1/ex1_counter_generic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_counter_generic_1_1 || ORIG_REF_NAME==ex1_counter_generic_1_1}]

# IP: bd/ex1/ip/ex1_xlconcat_3_0/ex1_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconcat_3_0 || ORIG_REF_NAME==ex1_xlconcat_3_0}]

# IP: bd/ex1/ip/ex1_Mux2_1_0_0/ex1_Mux2_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_Mux2_1_0_0 || ORIG_REF_NAME==ex1_Mux2_1_0_0}]

# IP: bd/ex1/ip/ex1_util_reduced_logic_0_0/ex1_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_util_reduced_logic_0_0 || ORIG_REF_NAME==ex1_util_reduced_logic_0_0}]

# IP: bd/ex1/ip/ex1_xlconcat_4_0/ex1_xlconcat_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconcat_4_0 || ORIG_REF_NAME==ex1_xlconcat_4_0}]

# IP: bd/ex1/ip/ex1_xlconstant_4_0/ex1_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconstant_4_0 || ORIG_REF_NAME==ex1_xlconstant_4_0}]

# XDC: bd/ex1/ex1_ooc.xdc
