# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/top/top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top}]

# IP: bd/top/ip/top_counter_generic_0_0/top_counter_generic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_counter_generic_0_0 || ORIG_REF_NAME==top_counter_generic_0_0}]

# IP: bd/top/ip/top_xlconstant_0_0/top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_0_0 || ORIG_REF_NAME==top_xlconstant_0_0}]

# IP: bd/top/ip/top_xlconstant_1_0/top_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_xlconstant_1_0 || ORIG_REF_NAME==top_xlconstant_1_0}]

# IP: bd/top/ip/top_Mux2_1_0_0/top_Mux2_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_Mux2_1_0_0 || ORIG_REF_NAME==top_Mux2_1_0_0}]

# IP: bd/top/ip/top_util_reduced_logic_0_0/top_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_util_reduced_logic_0_0 || ORIG_REF_NAME==top_util_reduced_logic_0_0}]

# XDC: bd/top/top_ooc.xdc
