# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jduarte/Documents/GitHub/CR/ProjetoV2/Projeto/Projeto.srcs/sources_1/bd/Project_design/ip/Project_design_lmb_bram_0/Project_design_lmb_bram_0.xci
# IP: The module: 'Project_design_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/ProjetoV2/Projeto/Projeto.srcs/sources_1/bd/Project_design/ip/Project_design_lmb_bram_0/Project_design_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_design_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/jduarte/Documents/GitHub/CR/ProjetoV2/Projeto/Projeto.srcs/sources_1/bd/Project_design/ip/Project_design_lmb_bram_0/Project_design_lmb_bram_0.xci
# IP: The module: 'Project_design_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/ProjetoV2/Projeto/Projeto.srcs/sources_1/bd/Project_design/ip/Project_design_lmb_bram_0/Project_design_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_design_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
