# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jduarte/Documents/GitHub/CR/Aula6/ex3/ex3.srcs/sources_1/bd/ex3_top/ip/ex3_top_blk_mem_gen_0_0/ex3_top_blk_mem_gen_0_0.xci
# IP: The module: 'ex3_top_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula6/ex3/ex3.srcs/sources_1/bd/ex3_top/ip/ex3_top_blk_mem_gen_0_0/ex3_top_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex3_top_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/jduarte/Documents/GitHub/CR/Aula6/ex3/ex3.srcs/sources_1/bd/ex3_top/ip/ex3_top_blk_mem_gen_0_0/ex3_top_blk_mem_gen_0_0.xci
# IP: The module: 'ex3_top_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula6/ex3/ex3.srcs/sources_1/bd/ex3_top/ip/ex3_top_blk_mem_gen_0_0/ex3_top_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex3_top_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
