# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/DebUART/DebUART.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART || ORIG_REF_NAME==DebUART}]

# IP: bd/DebUART/ip/DebUART_microblaze_0_0/DebUART_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_microblaze_0_0 || ORIG_REF_NAME==DebUART_microblaze_0_0}]

# IP: bd/DebUART/ip/DebUART_dlmb_v10_0/DebUART_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_dlmb_v10_0 || ORIG_REF_NAME==DebUART_dlmb_v10_0}]

# IP: bd/DebUART/ip/DebUART_ilmb_v10_0/DebUART_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_ilmb_v10_0 || ORIG_REF_NAME==DebUART_ilmb_v10_0}]

# IP: bd/DebUART/ip/DebUART_dlmb_bram_if_cntlr_0/DebUART_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DebUART_dlmb_bram_if_cntlr_0}]

# IP: bd/DebUART/ip/DebUART_ilmb_bram_if_cntlr_0/DebUART_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DebUART_ilmb_bram_if_cntlr_0}]

# IP: bd/DebUART/ip/DebUART_lmb_bram_0/DebUART_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_lmb_bram_0 || ORIG_REF_NAME==DebUART_lmb_bram_0}]

# IP: bd/DebUART/ip/DebUART_microblaze_0_axi_periph_0/DebUART_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DebUART_microblaze_0_axi_periph_0}]

# IP: bd/DebUART/ip/DebUART_mdm_1_0/DebUART_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_mdm_1_0 || ORIG_REF_NAME==DebUART_mdm_1_0}]

# IP: bd/DebUART/ip/DebUART_clk_wiz_1_0/DebUART_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_clk_wiz_1_0 || ORIG_REF_NAME==DebUART_clk_wiz_1_0}]

# IP: bd/DebUART/ip/DebUART_rst_clk_wiz_1_100M_0/DebUART_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DebUART_rst_clk_wiz_1_100M_0}]

# IP: bd/DebUART/ip/DebUART_axi_gpio_0_0/DebUART_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_axi_gpio_0_0 || ORIG_REF_NAME==DebUART_axi_gpio_0_0}]

# IP: bd/DebUART/ip/DebUART_xbar_0/DebUART_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xbar_0 || ORIG_REF_NAME==DebUART_xbar_0}]

# IP: bd/DebUART/ip/DebUART_xlslice_0_1/DebUART_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlslice_0_1 || ORIG_REF_NAME==DebUART_xlslice_0_1}]

# IP: bd/DebUART/ip/DebUART_xlslice_0_2/DebUART_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlslice_0_2 || ORIG_REF_NAME==DebUART_xlslice_0_2}]

# IP: bd/DebUART/ip/DebUART_xlslice_1_0/DebUART_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlslice_1_0 || ORIG_REF_NAME==DebUART_xlslice_1_0}]

# IP: bd/DebUART/ip/DebUART_BinToBCD16_0_0/DebUART_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_BinToBCD16_0_0 || ORIG_REF_NAME==DebUART_BinToBCD16_0_0}]

# IP: bd/DebUART/ip/DebUART_BinToBCD16_0_1/DebUART_BinToBCD16_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_BinToBCD16_0_1 || ORIG_REF_NAME==DebUART_BinToBCD16_0_1}]

# IP: bd/DebUART/ip/DebUART_xlslice_3_0/DebUART_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlslice_3_0 || ORIG_REF_NAME==DebUART_xlslice_3_0}]

# IP: bd/DebUART/ip/DebUART_xlslice_4_0/DebUART_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlslice_4_0 || ORIG_REF_NAME==DebUART_xlslice_4_0}]

# IP: bd/DebUART/ip/DebUART_xlconstant_1_0/DebUART_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlconstant_1_0 || ORIG_REF_NAME==DebUART_xlconstant_1_0}]

# IP: bd/DebUART/ip/DebUART_xlconcat_0_0/DebUART_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlconcat_0_0 || ORIG_REF_NAME==DebUART_xlconcat_0_0}]

# IP: bd/DebUART/ip/DebUART_xlconstant_2_0/DebUART_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlconstant_2_0 || ORIG_REF_NAME==DebUART_xlconstant_2_0}]

# IP: bd/DebUART/ip/DebUART_xlconstant_3_0/DebUART_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlconstant_3_0 || ORIG_REF_NAME==DebUART_xlconstant_3_0}]

# IP: bd/DebUART/ip/DebUART_EightDispControl_0_0/DebUART_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_EightDispControl_0_0 || ORIG_REF_NAME==DebUART_EightDispControl_0_0}]

# IP: bd/DebUART/ip/DebUART_blk_mem_gen_0_0/DebUART_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_blk_mem_gen_0_0 || ORIG_REF_NAME==DebUART_blk_mem_gen_0_0}]

# IP: bd/DebUART/ip/DebUART_counter_generic_0_0/DebUART_counter_generic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_counter_generic_0_0 || ORIG_REF_NAME==DebUART_counter_generic_0_0}]

# IP: bd/DebUART/ip/DebUART_xlconstant_4_0/DebUART_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlconstant_4_0 || ORIG_REF_NAME==DebUART_xlconstant_4_0}]

# IP: bd/DebUART/ip/DebUART_concat_memory_0_0/DebUART_concat_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_concat_memory_0_0 || ORIG_REF_NAME==DebUART_concat_memory_0_0}]

# IP: bd/DebUART/ip/DebUART_SliceMemory_0_0/DebUART_SliceMemory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_SliceMemory_0_0 || ORIG_REF_NAME==DebUART_SliceMemory_0_0}]

# IP: bd/DebUART/ip/DebUART_blk_mem_gen_1_0/DebUART_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_blk_mem_gen_1_0 || ORIG_REF_NAME==DebUART_blk_mem_gen_1_0}]

# IP: bd/DebUART/ip/DebUART_xlslice_5_0/DebUART_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlslice_5_0 || ORIG_REF_NAME==DebUART_xlslice_5_0}]

# IP: bd/DebUART/ip/DebUART_sort_0_1/DebUART_sort_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_sort_0_1 || ORIG_REF_NAME==DebUART_sort_0_1}]

# IP: bd/DebUART/ip/DebUART_xlconcat_2_0/DebUART_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlconcat_2_0 || ORIG_REF_NAME==DebUART_xlconcat_2_0}]

# IP: bd/DebUART/ip/DebUART_xlconstant_0_1/DebUART_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DebUART_xlconstant_0_1 || ORIG_REF_NAME==DebUART_xlconstant_0_1}]

# XDC: bd/DebUART/ip/DebUART_microblaze_0_0/DebUART_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_microblaze_0_0 || ORIG_REF_NAME==DebUART_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/DebUART/ip/DebUART_microblaze_0_0/DebUART_microblaze_0_0_ooc_debug.xdc

# XDC: bd/DebUART/ip/DebUART_microblaze_0_0/DebUART_microblaze_0_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_dlmb_v10_0/DebUART_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_dlmb_v10_0 || ORIG_REF_NAME==DebUART_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/DebUART/ip/DebUART_dlmb_v10_0/DebUART_dlmb_v10_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_ilmb_v10_0/DebUART_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_ilmb_v10_0 || ORIG_REF_NAME==DebUART_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/DebUART/ip/DebUART_ilmb_v10_0/DebUART_ilmb_v10_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_dlmb_bram_if_cntlr_0/DebUART_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_ilmb_bram_if_cntlr_0/DebUART_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_lmb_bram_0/DebUART_lmb_bram_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_mdm_1_0/DebUART_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_mdm_1_0 || ORIG_REF_NAME==DebUART_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/DebUART/ip/DebUART_mdm_1_0/DebUART_mdm_1_0_ooc_trace.xdc

# XDC: bd/DebUART/ip/DebUART_mdm_1_0/DebUART_mdm_1_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_clk_wiz_1_0/DebUART_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_clk_wiz_1_0 || ORIG_REF_NAME==DebUART_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/DebUART/ip/DebUART_clk_wiz_1_0/DebUART_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_clk_wiz_1_0 || ORIG_REF_NAME==DebUART_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/DebUART/ip/DebUART_clk_wiz_1_0/DebUART_clk_wiz_1_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_rst_clk_wiz_1_100M_0/DebUART_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DebUART_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/DebUART/ip/DebUART_rst_clk_wiz_1_100M_0/DebUART_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DebUART_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/DebUART/ip/DebUART_rst_clk_wiz_1_100M_0/DebUART_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_axi_gpio_0_0/DebUART_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_axi_gpio_0_0 || ORIG_REF_NAME==DebUART_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/DebUART/ip/DebUART_axi_gpio_0_0/DebUART_axi_gpio_0_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_axi_gpio_0_0/DebUART_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_axi_gpio_0_0 || ORIG_REF_NAME==DebUART_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/DebUART/ip/DebUART_xbar_0/DebUART_xbar_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_blk_mem_gen_0_0/DebUART_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/DebUART/ip/DebUART_counter_generic_0_0/constrs_1/imports/Desktop/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DebUART_counter_generic_0_0 || ORIG_REF_NAME==DebUART_counter_generic_0_0}] {/U0 }]/U0 ]]

# XDC: bd/DebUART/ip/DebUART_blk_mem_gen_1_0/DebUART_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/DebUART/DebUART_ooc.xdc
