webtalk_init -webtalk_dir C:/Users/jduarte/Documents/GitHub/CR/Aula6/ex7_top/ex7_top.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 04 23:29:15 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1756540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e6b07ff7-8a1d-4c35-a328-583eb82d622e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "791b6979-c34b-4b0d-9bcf-3973ea0730e9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "21.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key chain -value "13631093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Nexys4/15000000:" -context "labtool\\usage"
webtalk_transmit -clientid 3535983137 -regid "" -xml C:/Users/jduarte/Documents/GitHub/CR/Aula6/ex7_top/ex7_top.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/jduarte/Documents/GitHub/CR/Aula6/ex7_top/ex7_top.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/jduarte/Documents/GitHub/CR/Aula6/ex7_top/ex7_top.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
