# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/Project_design/Project_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design || ORIG_REF_NAME==Project_design}]

# IP: bd/Project_design/ip/Project_design_microblaze_0_0/Project_design_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_microblaze_0_0 || ORIG_REF_NAME==Project_design_microblaze_0_0}]

# IP: bd/Project_design/ip/Project_design_dlmb_v10_0/Project_design_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_dlmb_v10_0 || ORIG_REF_NAME==Project_design_dlmb_v10_0}]

# IP: bd/Project_design/ip/Project_design_ilmb_v10_0/Project_design_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_ilmb_v10_0 || ORIG_REF_NAME==Project_design_ilmb_v10_0}]

# IP: bd/Project_design/ip/Project_design_dlmb_bram_if_cntlr_0/Project_design_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Project_design_dlmb_bram_if_cntlr_0}]

# IP: bd/Project_design/ip/Project_design_ilmb_bram_if_cntlr_0/Project_design_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Project_design_ilmb_bram_if_cntlr_0}]

# IP: bd/Project_design/ip/Project_design_lmb_bram_0/Project_design_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_lmb_bram_0 || ORIG_REF_NAME==Project_design_lmb_bram_0}]

# IP: bd/Project_design/ip/Project_design_microblaze_0_axi_periph_0/Project_design_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Project_design_microblaze_0_axi_periph_0}]

# IP: bd/Project_design/ip/Project_design_mdm_1_0/Project_design_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_mdm_1_0 || ORIG_REF_NAME==Project_design_mdm_1_0}]

# IP: bd/Project_design/ip/Project_design_clk_wiz_1_0/Project_design_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_clk_wiz_1_0 || ORIG_REF_NAME==Project_design_clk_wiz_1_0}]

# IP: bd/Project_design/ip/Project_design_rst_clk_wiz_1_100M_0/Project_design_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Project_design_rst_clk_wiz_1_100M_0}]

# IP: bd/Project_design/ip/Project_design_axi_gpio_0_0/Project_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_axi_gpio_0_0 || ORIG_REF_NAME==Project_design_axi_gpio_0_0}]

# IP: bd/Project_design/ip/Project_design_xbar_0/Project_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xbar_0 || ORIG_REF_NAME==Project_design_xbar_0}]

# IP: bd/Project_design/ip/Project_design_xlslice_0_0/Project_design_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_0_0 || ORIG_REF_NAME==Project_design_xlslice_0_0}]

# IP: bd/Project_design/ip/Project_design_xlslice_0_1/Project_design_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_0_1 || ORIG_REF_NAME==Project_design_xlslice_0_1}]

# IP: bd/Project_design/ip/Project_design_xlslice_1_0/Project_design_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_1_0 || ORIG_REF_NAME==Project_design_xlslice_1_0}]

# IP: bd/Project_design/ip/Project_design_blk_mem_gen_1_0/Project_design_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_blk_mem_gen_1_0 || ORIG_REF_NAME==Project_design_blk_mem_gen_1_0}]

# IP: bd/Project_design/ip/Project_design_counter_generic_0_0/Project_design_counter_generic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_counter_generic_0_0 || ORIG_REF_NAME==Project_design_counter_generic_0_0}]

# IP: bd/Project_design/ip/Project_design_xlconstant_0_0/Project_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconstant_0_0 || ORIG_REF_NAME==Project_design_xlconstant_0_0}]

# IP: bd/Project_design/ip/Project_design_xlconstant_1_0/Project_design_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconstant_1_0 || ORIG_REF_NAME==Project_design_xlconstant_1_0}]

# IP: bd/Project_design/ip/Project_design_BinToBCD16_0_0/Project_design_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_BinToBCD16_0_0 || ORIG_REF_NAME==Project_design_BinToBCD16_0_0}]

# IP: bd/Project_design/ip/Project_design_xlslice_3_0/Project_design_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_3_0 || ORIG_REF_NAME==Project_design_xlslice_3_0}]

# IP: bd/Project_design/ip/Project_design_xlslice_3_1/Project_design_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_3_1 || ORIG_REF_NAME==Project_design_xlslice_3_1}]

# IP: bd/Project_design/ip/Project_design_xlconstant_2_0/Project_design_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconstant_2_0 || ORIG_REF_NAME==Project_design_xlconstant_2_0}]

# IP: bd/Project_design/ip/Project_design_xlconstant_3_0/Project_design_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconstant_3_0 || ORIG_REF_NAME==Project_design_xlconstant_3_0}]

# IP: bd/Project_design/ip/Project_design_xlconcat_0_0/Project_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconcat_0_0 || ORIG_REF_NAME==Project_design_xlconcat_0_0}]

# IP: bd/Project_design/ip/Project_design_BinToBCD16_0_1/Project_design_BinToBCD16_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_BinToBCD16_0_1 || ORIG_REF_NAME==Project_design_BinToBCD16_0_1}]

# IP: bd/Project_design/ip/Project_design_EightDispControl_0_0/Project_design_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_EightDispControl_0_0 || ORIG_REF_NAME==Project_design_EightDispControl_0_0}]

# IP: bd/Project_design/ip/Project_design_xlslice_5_0/Project_design_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlslice_5_0 || ORIG_REF_NAME==Project_design_xlslice_5_0}]

# IP: bd/Project_design/ip/Project_design_xlconstant_4_0/Project_design_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_xlconstant_4_0 || ORIG_REF_NAME==Project_design_xlconstant_4_0}]

# IP: bd/Project_design/ip/Project_design_auto_pc_0/Project_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_auto_pc_0 || ORIG_REF_NAME==Project_design_auto_pc_0}]

# IP: bd/Project_design/ip/Project_design_auto_pc_1/Project_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Project_design_auto_pc_1 || ORIG_REF_NAME==Project_design_auto_pc_1}]

# XDC: bd/Project_design/Project_design_ooc.xdc
