# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex5/ex5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5 || ORIG_REF_NAME==ex5}]

# IP: bd/ex5/ip/ex5_blk_mem_gen_0_0/ex5_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_blk_mem_gen_0_0 || ORIG_REF_NAME==ex5_blk_mem_gen_0_0}]

# IP: bd/ex5/ip/ex5_blk_mem_gen_1_0/ex5_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_blk_mem_gen_1_0 || ORIG_REF_NAME==ex5_blk_mem_gen_1_0}]

# IP: bd/ex5/ip/ex5_blk_mem_gen_2_0/ex5_blk_mem_gen_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_blk_mem_gen_2_0 || ORIG_REF_NAME==ex5_blk_mem_gen_2_0}]

# IP: bd/ex5/ip/ex5_blk_mem_gen_3_0/ex5_blk_mem_gen_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_blk_mem_gen_3_0 || ORIG_REF_NAME==ex5_blk_mem_gen_3_0}]

# IP: bd/ex5/ip/ex5_Mux4_1_0_0/ex5_Mux4_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_Mux4_1_0_0 || ORIG_REF_NAME==ex5_Mux4_1_0_0}]

# IP: bd/ex5/ip/ex5_xlconcat_0_0/ex5_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconcat_0_0 || ORIG_REF_NAME==ex5_xlconcat_0_0}]

# XDC: bd/ex5/ex5_ooc.xdc
