# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2_counter_que_vai_funcionar/ex2_counter_que_vai_funcionar.cache/wt [current_project]
set_property parent.project_path C:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2_counter_que_vai_funcionar/ex2_counter_que_vai_funcionar.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/users/jduarte/documents/github/cr/aula5/ex2_counter_que_vai_funcionar/ex2_counter_que_vai_funcionar.srcs [current_project]
set_property ip_output_repo c:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2_counter_que_vai_funcionar/ex2_counter_que_vai_funcionar.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2_counter_que_vai_funcionar/ex2_counter_que_vai_funcionar.srcs/sources_1/new/counter_between.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2_counter_que_vai_funcionar/ex2_counter_que_vai_funcionar.srcs/constrs_1/imports/CR/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2_counter_que_vai_funcionar/ex2_counter_que_vai_funcionar.srcs/constrs_1/imports/CR/Nexys4_Master.xdc]


synth_design -top counter_between -part xc7a100tcsg324-3


write_checkpoint -force -noxdef counter_between.dcp

catch { report_utilization -file counter_between_utilization_synth.rpt -pb counter_between_utilization_synth.pb }
