# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2/ex2.srcs/sources_1/bd/ex2_top/ip/ex2_top_number_of_ones_0_1/ex2_top_number_of_ones_0_1.xci
# IP: The module: 'ex2_top_number_of_ones_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2/ex2.srcs/sources_1/bd/ex2_top/ip/ex2_top_number_of_ones_0_1/constrs_1/imports/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex2_top_number_of_ones_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2/ex2.srcs/sources_1/bd/ex2_top/ip/ex2_top_number_of_ones_0_1/ex2_top_number_of_ones_0_1.xci
# IP: The module: 'ex2_top_number_of_ones_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula5/ex2/ex2.srcs/sources_1/bd/ex2_top/ip/ex2_top_number_of_ones_0_1/constrs_1/imports/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex2_top_number_of_ones_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
