# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jduarte/Documents/GitHub/CR/Aula3/ex5/ex5.srcs/sources_1/bd/ex5/ip/ex5_blk_mem_gen_2_0/ex5_blk_mem_gen_2_0.xci
# IP: The module: 'ex5_blk_mem_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula3/ex5/ex5.srcs/sources_1/bd/ex5/ip/ex5_blk_mem_gen_2_0/ex5_blk_mem_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex5_blk_mem_gen_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/jduarte/Documents/GitHub/CR/Aula3/ex5/ex5.srcs/sources_1/bd/ex5/ip/ex5_blk_mem_gen_2_0/ex5_blk_mem_gen_2_0.xci
# IP: The module: 'ex5_blk_mem_gen_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula3/ex5/ex5.srcs/sources_1/bd/ex5/ip/ex5_blk_mem_gen_2_0/ex5_blk_mem_gen_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex5_blk_mem_gen_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
