# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex1/ex1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1 || ORIG_REF_NAME==ex1}]

# IP: bd/ex1/ip/ex1_blk_mem_gen_0_0/ex1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_blk_mem_gen_0_0 || ORIG_REF_NAME==ex1_blk_mem_gen_0_0}]

# IP: bd/ex1/ip/ex1_counter_generic_0_0/ex1_counter_generic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_counter_generic_0_0 || ORIG_REF_NAME==ex1_counter_generic_0_0}]

# IP: bd/ex1/ip/ex1_xlconstant_0_0/ex1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconstant_0_0 || ORIG_REF_NAME==ex1_xlconstant_0_0}]

# IP: bd/ex1/ip/ex1_EightDispControl_0_0/ex1_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_EightDispControl_0_0 || ORIG_REF_NAME==ex1_EightDispControl_0_0}]

# IP: bd/ex1/ip/ex1_xlslice_0_0/ex1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_0_0 || ORIG_REF_NAME==ex1_xlslice_0_0}]

# IP: bd/ex1/ip/ex1_xlslice_0_1/ex1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_0_1 || ORIG_REF_NAME==ex1_xlslice_0_1}]

# IP: bd/ex1/ip/ex1_xlslice_0_2/ex1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_0_2 || ORIG_REF_NAME==ex1_xlslice_0_2}]

# IP: bd/ex1/ip/ex1_xlslice_2_0/ex1_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_2_0 || ORIG_REF_NAME==ex1_xlslice_2_0}]

# IP: bd/ex1/ip/ex1_xlslice_2_1/ex1_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_2_1 || ORIG_REF_NAME==ex1_xlslice_2_1}]

# IP: bd/ex1/ip/ex1_xlslice_4_0/ex1_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_4_0 || ORIG_REF_NAME==ex1_xlslice_4_0}]

# IP: bd/ex1/ip/ex1_xlslice_5_0/ex1_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_5_0 || ORIG_REF_NAME==ex1_xlslice_5_0}]

# IP: bd/ex1/ip/ex1_xlslice_6_0/ex1_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlslice_6_0 || ORIG_REF_NAME==ex1_xlslice_6_0}]

# XDC: bd/ex1/ex1_ooc.xdc
