# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2/ex2.cache/wt [current_project]
set_property parent.project_path C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2/ex2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2/ex2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex1/vector512_random.coe
read_vhdl -library xil_defaultlib C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2/ex2.srcs/sources_1/new/max_min_FSM.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2/ex2.srcs/constrs_1/imports/CR/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2/ex2.srcs/constrs_1/imports/CR/Nexys4_Master.xdc]


synth_design -top max_min_FSM -part xc7a100tcsg324-3


write_checkpoint -force -noxdef max_min_FSM.dcp

catch { report_utilization -file max_min_FSM_utilization_synth.rpt -pb max_min_FSM_utilization_synth.pb }
