# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jduarte/Documents/GitHub/CR/Projeto/MicroBlaze_Trivial/MicroBlaze_Trivial.srcs/sources_1/bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0.xci
# IP: The module: 'MB_to_display_text_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Projeto/MicroBlaze_Trivial/MicroBlaze_Trivial.srcs/sources_1/bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_to_display_text_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Projeto/MicroBlaze_Trivial/MicroBlaze_Trivial.srcs/sources_1/bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_to_display_text_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Projeto/MicroBlaze_Trivial/MicroBlaze_Trivial.srcs/sources_1/bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_to_display_text_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/jduarte/Documents/GitHub/CR/Projeto/MicroBlaze_Trivial/MicroBlaze_Trivial.srcs/sources_1/bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0.xci
# IP: The module: 'MB_to_display_text_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Projeto/MicroBlaze_Trivial/MicroBlaze_Trivial.srcs/sources_1/bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_to_display_text_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Projeto/MicroBlaze_Trivial/MicroBlaze_Trivial.srcs/sources_1/bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_to_display_text_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Projeto/MicroBlaze_Trivial/MicroBlaze_Trivial.srcs/sources_1/bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_to_display_text_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
