# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/ip/ex2_top_max_min_FSM_0_0/ex2_top_max_min_FSM_0_0.xci
# IP: The module: 'ex2_top_max_min_FSM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/ip/ex2_top_max_min_FSM_0_0/ex2.srcs/constrs_1/imports/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex2_top_max_min_FSM_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/ip/ex2_top_max_min_FSM_0_0/ex2_top_max_min_FSM_0_0.xci
# IP: The module: 'ex2_top_max_min_FSM_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula4/ex2_top/ex2_top.srcs/sources_1/bd/ex2_top/ip/ex2_top_max_min_FSM_0_0/ex2.srcs/constrs_1/imports/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex2_top_max_min_FSM_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
