# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/MB_to_display_text/MB_to_display_text.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text || ORIG_REF_NAME==MB_to_display_text}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_microblaze_0_0/MB_to_display_text_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_microblaze_0_0 || ORIG_REF_NAME==MB_to_display_text_microblaze_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_dlmb_v10_0/MB_to_display_text_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_dlmb_v10_0 || ORIG_REF_NAME==MB_to_display_text_dlmb_v10_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_ilmb_v10_0/MB_to_display_text_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_ilmb_v10_0 || ORIG_REF_NAME==MB_to_display_text_ilmb_v10_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_dlmb_bram_if_cntlr_0/MB_to_display_text_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_to_display_text_dlmb_bram_if_cntlr_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_ilmb_bram_if_cntlr_0/MB_to_display_text_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_to_display_text_ilmb_bram_if_cntlr_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_lmb_bram_0/MB_to_display_text_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_lmb_bram_0 || ORIG_REF_NAME==MB_to_display_text_lmb_bram_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_microblaze_0_axi_periph_0/MB_to_display_text_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB_to_display_text_microblaze_0_axi_periph_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_mdm_1_0/MB_to_display_text_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_mdm_1_0 || ORIG_REF_NAME==MB_to_display_text_mdm_1_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_clk_wiz_1_0 || ORIG_REF_NAME==MB_to_display_text_clk_wiz_1_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_rst_clk_wiz_1_100M_0/MB_to_display_text_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_to_display_text_rst_clk_wiz_1_100M_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_axi_gpio_0_0/MB_to_display_text_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_axi_gpio_0_0 || ORIG_REF_NAME==MB_to_display_text_axi_gpio_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xbar_0/MB_to_display_text_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xbar_0 || ORIG_REF_NAME==MB_to_display_text_xbar_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_blk_mem_gen_0_0/MB_to_display_text_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_blk_mem_gen_0_0 || ORIG_REF_NAME==MB_to_display_text_blk_mem_gen_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlslice_0_0/MB_to_display_text_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlslice_0_0 || ORIG_REF_NAME==MB_to_display_text_xlslice_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlslice_1_0/MB_to_display_text_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlslice_1_0 || ORIG_REF_NAME==MB_to_display_text_xlslice_1_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlslice_2_0/MB_to_display_text_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlslice_2_0 || ORIG_REF_NAME==MB_to_display_text_xlslice_2_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_counter_generic_0_0/MB_to_display_text_counter_generic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_counter_generic_0_0 || ORIG_REF_NAME==MB_to_display_text_counter_generic_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlconstant_0_0/MB_to_display_text_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlconstant_0_0 || ORIG_REF_NAME==MB_to_display_text_xlconstant_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_EightDispControl_0_0/MB_to_display_text_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_EightDispControl_0_0 || ORIG_REF_NAME==MB_to_display_text_EightDispControl_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_BinToBCD16_0_0/MB_to_display_text_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_BinToBCD16_0_0 || ORIG_REF_NAME==MB_to_display_text_BinToBCD16_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlconstant_1_0/MB_to_display_text_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlconstant_1_0 || ORIG_REF_NAME==MB_to_display_text_xlconstant_1_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlconstant_2_0/MB_to_display_text_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlconstant_2_0 || ORIG_REF_NAME==MB_to_display_text_xlconstant_2_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlslice_3_0/MB_to_display_text_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlslice_3_0 || ORIG_REF_NAME==MB_to_display_text_xlslice_3_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_BinToBCD16_0_1/MB_to_display_text_BinToBCD16_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_BinToBCD16_0_1 || ORIG_REF_NAME==MB_to_display_text_BinToBCD16_0_1}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlslice_4_0/MB_to_display_text_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlslice_4_0 || ORIG_REF_NAME==MB_to_display_text_xlslice_4_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlconcat_0_0/MB_to_display_text_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlconcat_0_0 || ORIG_REF_NAME==MB_to_display_text_xlconcat_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_xlconstant_3_0/MB_to_display_text_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_xlconstant_3_0 || ORIG_REF_NAME==MB_to_display_text_xlconstant_3_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_auto_pc_0/MB_to_display_text_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_auto_pc_0 || ORIG_REF_NAME==MB_to_display_text_auto_pc_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_auto_pc_1/MB_to_display_text_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_auto_pc_1 || ORIG_REF_NAME==MB_to_display_text_auto_pc_1}]

# XDC: bd/MB_to_display_text/MB_to_display_text_ooc.xdc
