# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jduarte/Documents/GitHub/CR/Aula6/counter_fromX_toY/counter_fromX_toY.cache/wt [current_project]
set_property parent.project_path C:/Users/jduarte/Documents/GitHub/CR/Aula6/counter_fromX_toY/counter_fromX_toY.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/jduarte/Documents/GitHub/CR/Aula6/counter_fromX_toY/counter_fromX_toY.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/jduarte/Documents/GitHub/CR/Aula6/counter_fromX_toY/counter_fromX_toY.srcs/sources_1/new/Counter_fromX_toY.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jduarte/Documents/GitHub/CR/Aula6/counter_fromX_toY/counter_fromX_toY.srcs/constrs_1/imports/CR/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/jduarte/Documents/GitHub/CR/Aula6/counter_fromX_toY/counter_fromX_toY.srcs/constrs_1/imports/CR/Nexys4_Master.xdc]


synth_design -top Counter_fromX_toY -part xc7a100tcsg324-3


write_checkpoint -force -noxdef Counter_fromX_toY.dcp

catch { report_utilization -file Counter_fromX_toY_utilization_synth.rpt -pb Counter_fromX_toY_utilization_synth.pb }
