# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex1_top/ex1_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top || ORIG_REF_NAME==ex1_top}]

# IP: bd/ex1_top/ip/ex1_top_blk_mem_gen_0_0/ex1_top_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_blk_mem_gen_0_0 || ORIG_REF_NAME==ex1_top_blk_mem_gen_0_0}]

# IP: bd/ex1_top/ip/ex1_top_CounterGenericNoClk_0_0/ex1_top_CounterGenericNoClk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_CounterGenericNoClk_0_0 || ORIG_REF_NAME==ex1_top_CounterGenericNoClk_0_0}]

# IP: bd/ex1_top/ip/ex1_top_ClkDividerN_0_0/ex1_top_ClkDividerN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_ClkDividerN_0_0 || ORIG_REF_NAME==ex1_top_ClkDividerN_0_0}]

# IP: bd/ex1_top/ip/ex1_top_xlconstant_0_0/ex1_top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_xlconstant_0_0 || ORIG_REF_NAME==ex1_top_xlconstant_0_0}]

# IP: bd/ex1_top/ip/ex1_top_xlconcat_0_0/ex1_top_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_xlconcat_0_0 || ORIG_REF_NAME==ex1_top_xlconcat_0_0}]

# IP: bd/ex1_top/ip/ex1_top_xlconstant_1_0/ex1_top_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_xlconstant_1_0 || ORIG_REF_NAME==ex1_top_xlconstant_1_0}]

# IP: bd/ex1_top/ip/ex1_top_BinToBCD16_0_0/ex1_top_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_BinToBCD16_0_0 || ORIG_REF_NAME==ex1_top_BinToBCD16_0_0}]

# IP: bd/ex1_top/ip/ex1_top_xlconstant_2_0/ex1_top_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_xlconstant_2_0 || ORIG_REF_NAME==ex1_top_xlconstant_2_0}]

# IP: bd/ex1_top/ip/ex1_top_EightDispControl_0_0/ex1_top_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_EightDispControl_0_0 || ORIG_REF_NAME==ex1_top_EightDispControl_0_0}]

# IP: bd/ex1_top/ip/ex1_top_xlconstant_2_1/ex1_top_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_top_xlconstant_2_1 || ORIG_REF_NAME==ex1_top_xlconstant_2_1}]

# XDC: bd/ex1_top/ex1_top_ooc.xdc
