# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/test_concat/test_concat.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat || ORIG_REF_NAME==test_concat}]

# IP: bd/test_concat/ip/test_concat_concat_memory_0_0/test_concat_concat_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat_concat_memory_0_0 || ORIG_REF_NAME==test_concat_concat_memory_0_0}]

# IP: bd/test_concat/ip/test_concat_blk_mem_gen_0_0/test_concat_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat_blk_mem_gen_0_0 || ORIG_REF_NAME==test_concat_blk_mem_gen_0_0}]

# IP: bd/test_concat/ip/test_concat_number_of_ones_0_0/test_concat_number_of_ones_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat_number_of_ones_0_0 || ORIG_REF_NAME==test_concat_number_of_ones_0_0}]

# IP: bd/test_concat/ip/test_concat_xlconstant_0_0/test_concat_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat_xlconstant_0_0 || ORIG_REF_NAME==test_concat_xlconstant_0_0}]

# IP: bd/test_concat/ip/test_concat_BinToBCD16_0_0/test_concat_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat_BinToBCD16_0_0 || ORIG_REF_NAME==test_concat_BinToBCD16_0_0}]

# IP: bd/test_concat/ip/test_concat_xlconstant_1_0/test_concat_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat_xlconstant_1_0 || ORIG_REF_NAME==test_concat_xlconstant_1_0}]

# IP: bd/test_concat/ip/test_concat_EightDispControl_0_0/test_concat_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat_EightDispControl_0_0 || ORIG_REF_NAME==test_concat_EightDispControl_0_0}]

# IP: bd/test_concat/ip/test_concat_xlconstant_2_0/test_concat_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat_xlconstant_2_0 || ORIG_REF_NAME==test_concat_xlconstant_2_0}]

# IP: bd/test_concat/ip/test_concat_IterativeSorterFSM_0_0/test_concat_IterativeSorterFSM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_concat_IterativeSorterFSM_0_0 || ORIG_REF_NAME==test_concat_IterativeSorterFSM_0_0}]

# XDC: bd/test_concat/test_concat_ooc.xdc
