# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex5/ex5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5 || ORIG_REF_NAME==ex5}]

# IP: bd/ex5/ip/ex5_blk_mem_gen_0_0/ex5_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_blk_mem_gen_0_0 || ORIG_REF_NAME==ex5_blk_mem_gen_0_0}]

# IP: bd/ex5/ip/ex5_getAddress_0_0/ex5_getAddress_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_getAddress_0_0 || ORIG_REF_NAME==ex5_getAddress_0_0}]

# IP: bd/ex5/ip/ex5_xlconstant_0_1/ex5_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconstant_0_1 || ORIG_REF_NAME==ex5_xlconstant_0_1}]

# IP: bd/ex5/ip/ex5_xlconstant_0_0/ex5_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconstant_0_0 || ORIG_REF_NAME==ex5_xlconstant_0_0}]

# IP: bd/ex5/ip/ex5_Counter_fromX_toY_0_0/ex5_Counter_fromX_toY_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_Counter_fromX_toY_0_0 || ORIG_REF_NAME==ex5_Counter_fromX_toY_0_0}]

# IP: bd/ex5/ip/ex5_getAddress_0_1/ex5_getAddress_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_getAddress_0_1 || ORIG_REF_NAME==ex5_getAddress_0_1}]

# IP: bd/ex5/ip/ex5_Mux4_1_0_0/ex5_Mux4_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_Mux4_1_0_0 || ORIG_REF_NAME==ex5_Mux4_1_0_0}]

# IP: bd/ex5/ip/ex5_xlconcat_1_0/ex5_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconcat_1_0 || ORIG_REF_NAME==ex5_xlconcat_1_0}]

# IP: bd/ex5/ip/ex5_ClkDividerN_0_1/ex5_ClkDividerN_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_ClkDividerN_0_1 || ORIG_REF_NAME==ex5_ClkDividerN_0_1}]

# IP: bd/ex5/ip/ex5_xlconstant_3_0/ex5_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconstant_3_0 || ORIG_REF_NAME==ex5_xlconstant_3_0}]

# IP: bd/ex5/ip/ex5_BubbleSorter_0_0/ex5_BubbleSorter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_BubbleSorter_0_0 || ORIG_REF_NAME==ex5_BubbleSorter_0_0}]

# IP: bd/ex5/ip/ex5_concat_memory_0_0/ex5_concat_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_concat_memory_0_0 || ORIG_REF_NAME==ex5_concat_memory_0_0}]

# IP: bd/ex5/ip/ex5_SliceMemory_0_0/ex5_SliceMemory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_SliceMemory_0_0 || ORIG_REF_NAME==ex5_SliceMemory_0_0}]

# IP: bd/ex5/ip/ex5_blk_mem_gen_1_0/ex5_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_blk_mem_gen_1_0 || ORIG_REF_NAME==ex5_blk_mem_gen_1_0}]

# IP: bd/ex5/ip/ex5_util_vector_logic_0_1/ex5_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_util_vector_logic_0_1 || ORIG_REF_NAME==ex5_util_vector_logic_0_1}]

# IP: bd/ex5/ip/ex5_util_vector_logic_0_2/ex5_util_vector_logic_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_util_vector_logic_0_2 || ORIG_REF_NAME==ex5_util_vector_logic_0_2}]

# IP: bd/ex5/ip/ex5_util_vector_logic_1_1/ex5_util_vector_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_util_vector_logic_1_1 || ORIG_REF_NAME==ex5_util_vector_logic_1_1}]

# IP: bd/ex5/ip/ex5_EightDispControl_0_0/ex5_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_EightDispControl_0_0 || ORIG_REF_NAME==ex5_EightDispControl_0_0}]

# IP: bd/ex5/ip/ex5_BinToBCD16_0_0/ex5_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_BinToBCD16_0_0 || ORIG_REF_NAME==ex5_BinToBCD16_0_0}]

# IP: bd/ex5/ip/ex5_xlconstant_2_0/ex5_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconstant_2_0 || ORIG_REF_NAME==ex5_xlconstant_2_0}]

# IP: bd/ex5/ip/ex5_xlconstant_2_1/ex5_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconstant_2_1 || ORIG_REF_NAME==ex5_xlconstant_2_1}]

# IP: bd/ex5/ip/ex5_xlconcat_0_1/ex5_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconcat_0_1 || ORIG_REF_NAME==ex5_xlconcat_0_1}]

# IP: bd/ex5/ip/ex5_xlconstant_4_0/ex5_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconstant_4_0 || ORIG_REF_NAME==ex5_xlconstant_4_0}]

# IP: bd/ex5/ip/ex5_xlconstant_4_1/ex5_xlconstant_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_xlconstant_4_1 || ORIG_REF_NAME==ex5_xlconstant_4_1}]

# IP: bd/ex5/ip/ex5_util_vector_logic_1_2/ex5_util_vector_logic_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex5_util_vector_logic_1_2 || ORIG_REF_NAME==ex5_util_vector_logic_1_2}]

# XDC: bd/ex5/ex5_ooc.xdc
