# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jduarte/Documents/GitHub/CR/Outros/Testar_stop_counter/Testar_stop_counter.srcs/sources_1/bd/top/ip/top_counter_generic_0_0/top_counter_generic_0_0.xci
# IP: The module: 'top_counter_generic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Outros/Testar_stop_counter/Testar_stop_counter.srcs/sources_1/bd/top/ip/top_counter_generic_0_0/constrs_1/imports/Desktop/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_counter_generic_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/jduarte/Documents/GitHub/CR/Outros/Testar_stop_counter/Testar_stop_counter.srcs/sources_1/bd/top/ip/top_counter_generic_0_0/top_counter_generic_0_0.xci
# IP: The module: 'top_counter_generic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Outros/Testar_stop_counter/Testar_stop_counter.srcs/sources_1/bd/top/ip/top_counter_generic_0_0/constrs_1/imports/Desktop/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_counter_generic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
