# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jduarte/Documents/GitHub/CR/TestePratico1/testeTop/testeTop.srcs/sources_1/bd/top_teste/ip/top_teste_blk_mem_gen_0_0/top_teste_blk_mem_gen_0_0.xci
# IP: The module: 'top_teste_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/TestePratico1/testeTop/testeTop.srcs/sources_1/bd/top_teste/ip/top_teste_blk_mem_gen_0_0/top_teste_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_teste_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/jduarte/Documents/GitHub/CR/TestePratico1/testeTop/testeTop.srcs/sources_1/bd/top_teste/ip/top_teste_blk_mem_gen_0_0/top_teste_blk_mem_gen_0_0.xci
# IP: The module: 'top_teste_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/TestePratico1/testeTop/testeTop.srcs/sources_1/bd/top_teste/ip/top_teste_blk_mem_gen_0_0/top_teste_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_teste_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
