# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Aula1_24Feb2017/Nexys4_Master.xdc

# Block Designs: bd/B/B.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B || ORIG_REF_NAME==B}]

# IP: bd/B/ip/B_Get2DigitsN_0_0/B_Get2DigitsN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B_Get2DigitsN_0_0 || ORIG_REF_NAME==B_Get2DigitsN_0_0}]

# XDC: bd/B/B_ooc.xdc
