# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex4/ex4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex4 || ORIG_REF_NAME==ex4}]

# IP: bd/ex4/ip/ex4_blk_mem_gen_0_0/ex4_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex4_blk_mem_gen_0_0 || ORIG_REF_NAME==ex4_blk_mem_gen_0_0}]

# IP: bd/ex4/ip/ex4_xlconstant_0_0/ex4_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex4_xlconstant_0_0 || ORIG_REF_NAME==ex4_xlconstant_0_0}]

# IP: bd/ex4/ip/ex4_xlconstant_1_0/ex4_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex4_xlconstant_1_0 || ORIG_REF_NAME==ex4_xlconstant_1_0}]

# IP: bd/ex4/ip/ex4_number_of_ones_0_0/ex4_number_of_ones_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex4_number_of_ones_0_0 || ORIG_REF_NAME==ex4_number_of_ones_0_0}]

# XDC: bd/ex4/ex4_ooc.xdc
