# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex3_top/ex3_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_top || ORIG_REF_NAME==ex3_top}]

# IP: bd/ex3_top/ip/ex3_top_max_0_1/ex3_top_max_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_top_max_0_1 || ORIG_REF_NAME==ex3_top_max_0_1}]

# IP: bd/ex3_top/ip/ex3_top_blk_mem_gen_0_0/ex3_top_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_top_blk_mem_gen_0_0 || ORIG_REF_NAME==ex3_top_blk_mem_gen_0_0}]

# IP: bd/ex3_top/ip/ex3_top_xlconcat_0_0/ex3_top_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_top_xlconcat_0_0 || ORIG_REF_NAME==ex3_top_xlconcat_0_0}]

# IP: bd/ex3_top/ip/ex3_top_concat_memory_0_0/ex3_top_concat_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_top_concat_memory_0_0 || ORIG_REF_NAME==ex3_top_concat_memory_0_0}]

# IP: bd/ex3_top/ip/ex3_top_c_addsub_0_0/ex3_top_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_top_c_addsub_0_0 || ORIG_REF_NAME==ex3_top_c_addsub_0_0}]

# XDC: bd/ex3_top/ex3_top_ooc.xdc
