# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/JoanaConde/Documents/CR/project_aula03_ex31/project_aula03_ex31.cache/wt [current_project]
set_property parent.project_path C:/Users/JoanaConde/Documents/CR/project_aula03_ex31/project_aula03_ex31.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Users/JoanaConde/Documents/CR/project_aula03_ex31/project_aula03_ex31.srcs [current_project]
set_property ip_output_repo c:/Users/JoanaConde/Documents/CR/project_aula03_ex31/project_aula03_ex31.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/JoanaConde/Documents/CR/project_aula03_ex31/project_aula03_ex31.srcs/sources_1/imports/new/MaxOnesCons.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/JoanaConde/Documents/CR/project_aula03_ex31/project_aula03_ex31.srcs/constrs_1/imports/Aula01/SDR_const.xdc
set_property used_in_implementation false [get_files C:/Users/JoanaConde/Documents/CR/project_aula03_ex31/project_aula03_ex31.srcs/constrs_1/imports/Aula01/SDR_const.xdc]


synth_design -top MaxOnesCons -part xc7a100tcsg324-1


write_checkpoint -force -noxdef MaxOnesCons.dcp

catch { report_utilization -file MaxOnesCons_utilization_synth.rpt -pb MaxOnesCons_utilization_synth.pb }
