# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/jduarte/Documents/GitHub/CR/Projeto/sort_even_odd_merge_e_desta/sort_even_odd_merge_e_desta.cache/wt [current_project]
set_property parent.project_path C:/Users/jduarte/Documents/GitHub/CR/Projeto/sort_even_odd_merge_e_desta/sort_even_odd_merge_e_desta.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/jduarte/Documents/GitHub/CR/Projeto/sort_even_odd_merge_e_desta/sort_even_odd_merge_e_desta.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/jduarte/Documents/GitHub/CR/Projeto/sort_even_odd_merge_e_desta/sort_even_odd_merge_e_desta.srcs/sources_1/imports/new/sort.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sort -part xc7a100tcsg324-3


write_checkpoint -force -noxdef sort.dcp

catch { report_utilization -file sort_utilization_synth.rpt -pb sort_utilization_synth.pb }
