# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jduarte/Documents/GitHub/CR/Aula5/Teste_counter_que_vai_funcionar/Teste_counter_que_vai_funcionar.srcs/sources_1/bd/teste/ip/teste_counter_between_0_0/teste_counter_between_0_0.xci
# IP: The module: 'teste_counter_between_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula5/Teste_counter_que_vai_funcionar/Teste_counter_que_vai_funcionar.srcs/sources_1/bd/teste/ip/teste_counter_between_0_0/constrs_1/imports/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'teste_counter_between_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/jduarte/Documents/GitHub/CR/Aula5/Teste_counter_que_vai_funcionar/Teste_counter_que_vai_funcionar.srcs/sources_1/bd/teste/ip/teste_counter_between_0_0/teste_counter_between_0_0.xci
# IP: The module: 'teste_counter_between_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jduarte/Documents/GitHub/CR/Aula5/Teste_counter_que_vai_funcionar/Teste_counter_que_vai_funcionar.srcs/sources_1/bd/teste/ip/teste_counter_between_0_0/constrs_1/imports/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'teste_counter_between_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
