# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/MB_to_display_text/MB_to_display_text.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text || ORIG_REF_NAME==MB_to_display_text}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_microblaze_0_0/MB_to_display_text_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_microblaze_0_0 || ORIG_REF_NAME==MB_to_display_text_microblaze_0_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_dlmb_v10_0/MB_to_display_text_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_dlmb_v10_0 || ORIG_REF_NAME==MB_to_display_text_dlmb_v10_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_ilmb_v10_0/MB_to_display_text_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_ilmb_v10_0 || ORIG_REF_NAME==MB_to_display_text_ilmb_v10_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_dlmb_bram_if_cntlr_0/MB_to_display_text_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_to_display_text_dlmb_bram_if_cntlr_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_ilmb_bram_if_cntlr_0/MB_to_display_text_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_to_display_text_ilmb_bram_if_cntlr_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_lmb_bram_0/MB_to_display_text_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_lmb_bram_0 || ORIG_REF_NAME==MB_to_display_text_lmb_bram_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_microblaze_0_axi_periph_0/MB_to_display_text_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB_to_display_text_microblaze_0_axi_periph_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_mdm_1_0/MB_to_display_text_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_mdm_1_0 || ORIG_REF_NAME==MB_to_display_text_mdm_1_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_clk_wiz_1_0/MB_to_display_text_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_clk_wiz_1_0 || ORIG_REF_NAME==MB_to_display_text_clk_wiz_1_0}]

# IP: bd/MB_to_display_text/ip/MB_to_display_text_rst_clk_wiz_1_100M_0/MB_to_display_text_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_to_display_text_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_to_display_text_rst_clk_wiz_1_100M_0}]

# XDC: bd/MB_to_display_text/MB_to_display_text_ooc.xdc
