# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/top_teste/top_teste.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_teste || ORIG_REF_NAME==top_teste}]

# IP: bd/top_teste/ip/top_teste_ClkDividerN_0_0/top_teste_ClkDividerN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_teste_ClkDividerN_0_0 || ORIG_REF_NAME==top_teste_ClkDividerN_0_0}]

# IP: bd/top_teste/ip/top_teste_FSM_control_0_0/top_teste_FSM_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_teste_FSM_control_0_0 || ORIG_REF_NAME==top_teste_FSM_control_0_0}]

# IP: bd/top_teste/ip/top_teste_sort_0_0/top_teste_sort_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_teste_sort_0_0 || ORIG_REF_NAME==top_teste_sort_0_0}]

# IP: bd/top_teste/ip/top_teste_blk_mem_gen_0_0/top_teste_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_teste_blk_mem_gen_0_0 || ORIG_REF_NAME==top_teste_blk_mem_gen_0_0}]

# IP: bd/top_teste/ip/top_teste_EightDispControl_0_0/top_teste_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_teste_EightDispControl_0_0 || ORIG_REF_NAME==top_teste_EightDispControl_0_0}]

# IP: bd/top_teste/ip/top_teste_xlconstant_0_0/top_teste_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_teste_xlconstant_0_0 || ORIG_REF_NAME==top_teste_xlconstant_0_0}]

# XDC: bd/top_teste/top_teste_ooc.xdc
